[template]
cargo_generate_version = ">=0.18.2"
ignore = [ "circuits/cargo-generate.toml" ]

[placeholders.circom-name]
type = "string"
prompt = "Name of the Circom circuit (snake_case)"

[placeholders.circom-name-camel-case]
type = "string"
prompt = "Name of the Circom circuit (camelCase)"

[placeholders.rust-name]
type = "string"
prompt = "Name of the Rust crate (snake_case)"

[placeholders.program-id]
type = "string"
prompt = "Solana program ID"
default = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[placeholders.type]
type = "string"
prompt = "Repo type (psp, circom)"
default = "psp"

[conditional.'type == "psp"']
ignore = [ "circuits/circuit_circom", "tests_circom", "programs_circom" ]

[conditional.'type == "circom"']
ignore = [ "circuits/circuit_psp", "tests_psp", "programs_psp" ]
